In [1]:
import pandas as pd
import numpy as np

D:\APPS\Anaconda\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
mart=pd.read_csv("bigmart_data.csv")

In [3]:
mart

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,20.750000,1,0.007565,13,107.8622,1,0,1,2181.288914
1,8.300000,4,0.038428,4,87.3198,1,1,1,2181.288914
2,14.600000,1,0.099575,11,241.7538,1,2,0,2181.288914
3,7.315000,1,0.015388,13,155.0340,1,1,1,2181.288914
4,12.792854,2,0.118599,4,234.2300,1,2,3,2181.288914
...,...,...,...,...,...,...,...,...,...
14199,6.865000,1,0.056783,13,214.5218,0,2,1,2778.383400
14200,8.380000,2,0.046982,0,108.1570,1,1,1,549.285000
14201,10.600000,1,0.035186,8,85.1224,2,1,1,1193.113600
14202,7.210000,2,0.145221,13,103.1332,1,2,2,1845.597600
14203,14.800000,1,0.044878,14,75.4670,2,0,1,765.670000

In [5]:
mart.columns

Index(['Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_Type',
       'Item_MRP', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type',
       'Item_Outlet_Sales'],
      dtype='object')

In [6]:
indep=mart[['Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_Type','Item_MRP', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type',]]
dep=mart[['Item_Outlet_Sales']]

In [7]:
indep

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,20.750000,1,0.007565,13,107.8622,1,0,1
1,8.300000,4,0.038428,4,87.3198,1,1,1
2,14.600000,1,0.099575,11,241.7538,1,2,0
3,7.315000,1,0.015388,13,155.0340,1,1,1
4,12.792854,2,0.118599,4,234.2300,1,2,3
...,...,...,...,...,...,...,...,...
14199,6.865000,1,0.056783,13,214.5218,0,2,1
14200,8.380000,2,0.046982,0,108.1570,1,1,1
14201,10.600000,1,0.035186,8,85.1224,2,1,1
14202,7.210000,2,0.145221,13,103.1332,1,2,2
14203,14.800000,1,0.044878,14,75.4670,2,0,1

In [8]:
dep

       Item_Outlet_Sales
0            2181.288914
1            2181.288914
2            2181.288914
3            2181.288914
4            2181.288914
...                  ...
14199        2778.383400
14200         549.285000
14201        1193.113600
14202        1845.597600
14203         765.670000

[14204 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(indep,dep,test_size=0.3,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
from sklearn.ensemble import GradientBoostingRegressor
regressor = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3)
regressor.fit(X_train, y_train)

D:\APPS\Anaconda\Lib\site-packages\sklearn\ensemble\_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GradientBoostingRegressor()

In [12]:
y_pred=regressor.predict(X_test)

In [13]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.3698886051079474